---
title: "Análise da base RAIS"
description: |
  Analisar a remuneração dos arquivista de documentos (CBO:4151-05)
author:
  - name: Pedro Barros
    url: https://example.com/norajones
date: 2022-01-22
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Esse é o meu primeiro projeto, então paciência, gente.


```{r}
#Pacotes utilizados nesta analise:
library(bigrquery)
library(dplyr)
library(ggplot2)

```

#Conectando
Conectando com o datalake da Base dos Dados:

```{r}
conexao <- bigrquery::dbConnect(
  bigrquery::bigquery(),
  project = "basedosdados",
  dataset = "br_me_rais",
  billing = "rais-pmsb"
)

bigrquery::bq_auth("pedrobarrosrjsp@gmail.com")

#Do jeito que esta, a consulta cobrou 270GB. Nao repita, seu doido.
microdados_arqdoc_2019 <- tbl(conexao, "microdados_vinculos") |>
  select(everything()) |>
   filter(
     ano == 2019,
     cbo_2002 == "415105" #Arquivista de documentos
   )

microdados_arqdoc_2019 <- collect(microdados_arqdoc_2019)

#Salvar saporra, ja que me custou 270GB.
microdados_arqdoc_2019 |>
  readr::write_rds(
    "~/ProjetosR/portfolio_pedro/data_raw/microdados_arqdoc_2019.rds"
  )

```

#Perguntas de pesquisa
1. Quanto ganha um arquivista?
1. Como a remuneração varia:
    1.regionalmente?
    1.por raça?
    1.por gênero?
1. Em que mês e região houve aceleração da contratação de arquivistas ao longo do ano?

```{r}
#Quanto ganha um arquivista?
microdados_arqdoc_2019 |>
  group_by(sigla_uf) |>
  summarise(remun_media = mean(valor_remuneracao_media)) |>
  arrange(desc(remun_media))

#Qual a idade media dos arquivistas?
microdados_arqdoc_2019 |>
  group_by(sigla_uf) |>
  summarise(idade_media = mean(idade)) |>
  arrange(desc())

#Como as admissoes variam ao longo do ano?
tabela_admissoes_mensais <- microdados_arqdoc_2019 |>
  filter(!is.na(mes_admissao)) |>
  #Tem uma cacetada de NA, entao filtrar NA e temerario.
  #Porem, pra seguir em frente, vamos assim mesmo...
  count(mes_admissao) 

tabela_admissoes_mensais |>
  knitr::kable()

tabela_admissoes_mensais |>
  ggplot(aes(x = mes_admissao, y = n))+
  geom_line(na.rm = TRUE)+
  scale_x_continuous(breaks = 1:12)+
  ylim(0, 600)


```











